In [785]:
from sklearn.preprocessing import StandardScaler
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [1085]:
df = pd.read_csv('Report20200501-20201030.csv', nrows=5000000,encoding='ISO-8859-1',parse_dates=['ï»¿"Date"'])

In [1086]:
#df['ï»¿"Date"'] = pd.to_datetime(df['ï»¿"Date"'],errors = 'coerce')
df['ï»¿"Date"']=df['ï»¿"Date"'].dt.day_name()

In [1087]:
df.describe().transpose()

,count,unique,top,freq
"ï»¿""Date""",5000000,7,Tuesday,1008420
User ID (v14) (evar14),5000000,211335,cmilcinovic,740
Service Line,4980854,108,Data Field Blank,3041907
Service Line Local,4980854,874,Data Field Blank,1961714
Service Area,4980854,60,Data Field Blank,833413
Service Area Local,4980854,502,Data Field Blank,825532
Member Firm,4980854,37,United States,3225007
Level Local,4980854,128,Senior,992505
Level,4980854,11,Senior,1250639
Function Local,4980854,47,Consulting,1528917
Function,4980854,11,Consulting,1708500
Deloitte Network Intranet (v51) (evar51),5000000,43,United States,3218492
Header Area Clicked (v55) (evar55),840665,6,App Launcher,441123
Header Item Clicked (v56) (evar56),840665,3487,SWIFT,109684
Search Result Clicked Subtype (v59) (evar59),1420754,5,Apps,797634
Search Result Clicked Title (v23) (evar23),1468477,65948,DTE: Deloitte Time & Expense,237250

In [1088]:
name='aascione'
dfd=df.loc[df['User ID (v14) (evar14)'] == name]
dfd

,"ï»¿""Date""",User ID (v14) (evar14),Service Line,Service Line Local,Service Area,Service Area Local,Member Firm,Level Local,Level,Function Local,Function,Deloitte Network Intranet (v51) (evar51),Header Area Clicked (v55) (evar55),Header Item Clicked (v56) (evar56),Search Result Clicked Subtype (v59) (evar59),Search Result Clicked Title (v23) (evar23)
496,Friday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
497,Friday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Pages,Web Template Central
186111,Monday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
186112,Monday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,KX Deloitte People Network
186113,Monday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Pages,TOD: Talent On Demand
369270,Tuesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
369271,Tuesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,STAFFIT
535357,Wednesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
535358,Wednesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,KX Deloitte People Network
694483,Thursday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
694484,Thursday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,KX Deloitte People Network
1237899,Tuesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
1237900,Tuesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,STAFFIT
1572648,Thursday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
1572649,Thursday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,STAFFIT
1572650,Thursday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Pages,TOD: Talent On Demand
1742085,Friday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
1742086,Friday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Pages,Poll Everywhere
2155171,Tuesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
2155172,Tuesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,STAFFIT
2155173,Tuesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Pages,TOD: Talent On Demand
2480454,Thursday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
2480455,Thursday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,STAFFIT
2878179,Tuesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
2878180,Tuesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,STAFFIT
3061281,Wednesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Pages,TOD: Talent On Demand
3674077,Monday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
3674078,Monday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,STAFFIT
4012295,Wednesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
4012296,Wednesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,STAFFIT
4346067,Friday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,STAFFIT
4563945,Monday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
4563946,Monday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,STAFFIT
4563947,Monday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Pages,TOD: Talent On Demand
4746609,Tuesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,NaN,NaN
4746610,Tuesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Apps,STAFFIT
4746611,Tuesday,aascione,Supply Chain and Network Operations,Supply Chain and Network Operations,Enterprise Technology and Performance,Enterprise Performance,United States,Senior,Senior,Consulting,Consulting,United States,NaN,NaN,Pages,TOD: Talent On Demand

In [1096]:
Group=df.groupby(['ï»¿"Date"','Service Line Local','Service Area Local','Function Local','Member Firm','Level Local','Deloitte Network Intranet (v51) (evar51)'])
group2=Group['User ID (v14) (evar14)'] 
group3=Group['Header Area Clicked (v55) (evar55)']
group4=Group['Header Item Clicked (v56) (evar56)']
group5=Group['Search Result Clicked Subtype (v59) (evar59)']
group6=Group['Search Result Clicked Title (v23) (evar23)']

In [1108]:
Output1=[]
Output2=[]
Output3=[]

for i,j in group2:
    Output1.append(list( dict.fromkeys(j.values)))
    
for i,j in group4:
    Output2.append(j.values)
    
for i,j in group6:
    Output3.append(j.values)

In [1115]:
indexes=[]
for a in Output1:
    if name in a:
        indexes.append(a)
    
#indexes

In [1116]:
pds=[]
for i in range(len(indexes)):
    pds.append(pd.DataFrame(Output1[Output1.index(indexes[i])]))

In [1117]:
vee = pd.concat(pds)

In [1118]:
vout=[]
for i in range(len(indexes)):
    vout.append(pd.DataFrame(Output2[Output1.index(indexes[i])],columns= ['Color']))
    vout.append(pd.DataFrame(Output3[Output1.index(indexes[i])],columns= ['Color']))


veeO=pd.concat(vout)
dups_color = veeO.pivot_table(index=['Color'], aggfunc='size').sort_values(ascending=False)
dups_color

Color
STAFFIT                         680
DTE: Deloitte Time & Expense    595
TOD: Talent On Demand           278
Talent On Demand                168
KX Deloitte People Network      161
                               ...
My Personal Information           1
Namrata Bhattacharjee             1
Namrata Nande                     1
Nancy Morton                      1
401(k) Plan                       1
Length: 607, dtype: int64

In [1119]:
#name='pdaniel'
L=df.loc[df['User ID (v14) (evar14)'] == name]
L1=pd.DataFrame(L[['Header Item Clicked (v56) (evar56)']],columns= ['Header Item Clicked (v56) (evar56)'])
L2=pd.DataFrame(L[['Search Result Clicked Title (v23) (evar23)']],columns= ['Search Result Clicked Title (v23) (evar23)'])

Li1=L1.rename(columns={"Header Item Clicked (v56) (evar56)": "Color"})
Li2=L2.rename(columns={"Search Result Clicked Title (v23) (evar23)": "Color"})

vee=pd.concat([Li1 ,Li2])
dups_color2 = vee.pivot_table(index=['Color'], aggfunc='size').sort_values(ascending=False)

In [1120]:
dups_color2

Color
STAFFIT                       11
TOD: Talent On Demand          6
KX Deloitte People Network     3
Web Template Central           1
Poll Everywhere                1
dtype: int64

In [1121]:
d1=pd.DataFrame(dups_color,columns= ['Count'])
d2=pd.DataFrame(dups_color2,columns= ['Count'])

In [1122]:
pd.concat([d1,d2])

                              Count
Color
STAFFIT                         680
DTE: Deloitte Time & Expense    595
TOD: Talent On Demand           278
Talent On Demand                168
KX Deloitte People Network      161
...                             ...
STAFFIT                          11
TOD: Talent On Demand             6
KX Deloitte People Network        3
Web Template Central              1
Poll Everywhere                   1

[612 rows x 1 columns]