In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import re
import numpy as np

In [6]:
meta_data = pd.read_csv('Report_user (3).csv',encoding='ISO-8859-1')
print('Original Size of Data:',meta_data.shape)
meta_data.dropna(subset = ['Tenure (yrs)', 'Service Line', 'Service Area', 'Office', 'Member Firm','Level','Function'],axis = 0, inplace = True)
print('Data Size after dropping rows with null values (based on abstract attribute):',meta_data.shape)

Original Size of Data: (2532437, 22)
Data Size after dropping rows with null values (based on abstract attribute): (2504903, 22)

In [7]:
meta_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2504903 entries, 60 to 2532436
Data columns (total 22 columns):
 #   Column                                        Dtype
---  ------                                        -----
 0   ï»¿"User ID (v14) (evar14)"                   object
 1   Tenure (yrs)                                  object
 2   Subregion                                     object
 3   Service Line                                  object
 4   Service Area                                  object
 5   Office                                        object
 6   Member Firm                                   object
 7   Level Local                                   object
 8   Level                                         object
 9   Function Local                                object
 10  Function                                      object
 11  Country                                       object
 12  Header Area Clicked (v55) (evar55)            object
 13  Header Item Clicked (v56) (evar56)            object
 14  Search Result Clicked Detail (v60) (evar60)   object
 15  Search Result Clicked Subtype (v59) (evar59)  object
 16  Search Result Clicked Title (v23) (evar23)    object
 17  Search Result Clicked Type (v58) (evar58)     object
 18  Search Type (v25) (evar25)                    object
 19  Search Terms (v26) (evar26)                   object
 20  Capability                                    object
 21  Breadcrumb (v9) (evar9)                       object
dtypes: object(22)
memory usage: 439.6+ MB

In [11]:
meta_data

,"ï»¿""User ID (v14) (evar14)""",Tenure (yrs),Subregion,Service Line,Service Area,Office,Member Firm,Level Local,Level,Function Local,...,Header Area Clicked (v55) (evar55),Header Item Clicked (v56) (evar56),Search Result Clicked Detail (v60) (evar60),Search Result Clicked Subtype (v59) (evar59),Search Result Clicked Title (v23) (evar23),Search Result Clicked Type (v58) (evar58),Search Type (v25) (evar25),Search Terms (v26) (evar26),Capability,Breadcrumb (v9) (evar9)
60,aaaarthi,Data Field Blank,Data Field Blank,Data Field Blank,Audit Services,Data Field Blank,United States,Junior Staff or Analyst,Junior Staff,Audit and Assurance,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Field Blank,NaN
61,aaaarthi,Data Field Blank,Data Field Blank,Data Field Blank,Audit Services,Data Field Blank,United States,Junior Staff or Analyst,Junior Staff,Audit and Assurance,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Field Blank,DeloitteNet > People & Practices > Practice Co...
62,aaaarthi,Data Field Blank,Data Field Blank,Data Field Blank,Audit Services,Data Field Blank,United States,Junior Staff or Analyst,Junior Staff,Audit and Assurance,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Field Blank,DeloitteNet > People & Practices > Practice Co...
63,aaaarthi,Data Field Blank,Data Field Blank,Data Field Blank,Audit Services,Data Field Blank,United States,Junior Staff or Analyst,Junior Staff,Audit and Assurance,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Field Blank,DeloitteNet > People & Practices > Practice Co...
64,aaaarthi,Data Field Blank,Data Field Blank,Data Field Blank,Audit Services,Data Field Blank,United States,Junior Staff or Analyst,Junior Staff,Audit and Assurance,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Field Blank,Home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2532432,zzuberi,6 to 10,Data Field Blank,Internal Audit,Accounting and Internal Controls,Data Field Blank,United States,Associate 6,Senior,Risk and Financial Advisory,...,NaN,NaN,Result title,Pages,TOD: Talent On Demand,Instant Find Result,Instant Find,talent on demand,Data Field Blank,NaN
2532433,zzuberi,6 to 10,Data Field Blank,Internal Audit,Accounting and Internal Controls,Data Field Blank,United States,Associate 6,Senior,Risk and Financial Advisory,...,NaN,NaN,Result title,Pages,TOD: Talent On Demand,Instant Find Result,Instant Find,TOD,Data Field Blank,NaN
2532434,zzwane,Less than 1,Data Field Blank,Data Field Blank,Human Capital,Data Field Blank,Africa,Junior Staff,Junior Staff,Consulting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Field Blank,Home
2532435,zzwane,Less than 1,Data Field Blank,Data Field Blank,Human Capital,Data Field Blank,Africa,Junior Staff,Junior Staff,Consulting,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data Field Blank,South Africa > UnityRedirection
2532436,zzwane,Less than 1,Data Field Blank,Data Field Blank,Human Capital,Data Field Blank,Africa,Junior Staff,Junior Staff,Consulting,...,NaN,NaN,NaN,NaN,NaN,NaN,Instant Find DIGS Search,4pl,Data Field Blank,NaN

In [12]:
print(meta_data[meta_data.duplicated(subset=['Tenure (yrs)', 'Service Line', 'Service Area', 'Office', 'Member Firm','Level','Function'], keep=False) == True])
meta_data.drop_duplicates(subset=['Tenure (yrs)', 'Service Line', 'Service Area', 'Office', 'Member Firm','Level','Function'],keep ='last',inplace=True)
print('Data Size after dropping duplicated data (based on abstract attribute):',meta_data.shape)

        ï»¿"User ID (v14) (evar14)"      Tenure (yrs)         Subregion  \
60                         aaaarthi  Data Field Blank  Data Field Blank
61                         aaaarthi  Data Field Blank  Data Field Blank
62                         aaaarthi  Data Field Blank  Data Field Blank
63                         aaaarthi  Data Field Blank  Data Field Blank
64                         aaaarthi  Data Field Blank  Data Field Blank
...                             ...               ...               ...
2532432                     zzuberi           6 to 10  Data Field Blank
2532433                     zzuberi           6 to 10  Data Field Blank
2532434                      zzwane       Less than 1  Data Field Blank
2532435                      zzwane       Less than 1  Data Field Blank
2532436                      zzwane       Less than 1  Data Field Blank

             Service Line                      Service Area            Office  \
60       Data Field Blank                    Audit Services  Data Field Blank
61       Data Field Blank                    Audit Services  Data Field Blank
62       Data Field Blank                    Audit Services  Data Field Blank
63       Data Field Blank                    Audit Services  Data Field Blank
64       Data Field Blank                    Audit Services  Data Field Blank
...                   ...                               ...               ...
2532432    Internal Audit  Accounting and Internal Controls  Data Field Blank
2532433    Internal Audit  Accounting and Internal Controls  Data Field Blank
2532434  Data Field Blank                     Human Capital  Data Field Blank
2532435  Data Field Blank                     Human Capital  Data Field Blank
2532436  Data Field Blank                     Human Capital  Data Field Blank

           Member Firm              Level Local         Level  \
60       United States  Junior Staff or Analyst  Junior Staff
61       United States  Junior Staff or Analyst  Junior Staff
62       United States  Junior Staff or Analyst  Junior Staff
63       United States  Junior Staff or Analyst  Junior Staff
64       United States  Junior Staff or Analyst  Junior Staff
...                ...                      ...           ...
2532432  United States              Associate 6        Senior
2532433  United States              Associate 6        Senior
2532434         Africa             Junior Staff  Junior Staff
2532435         Africa             Junior Staff  Junior Staff
2532436         Africa             Junior Staff  Junior Staff

                      Function Local  ... Header Area Clicked (v55) (evar55)  \
60               Audit and Assurance  ...                                NaN
61               Audit and Assurance  ...                                NaN
62               Audit and Assurance  ...                                NaN
63               Audit and Assurance  ...                                NaN
64               Audit and Assurance  ...                                NaN
...                              ...  ...                                ...
2532432  Risk and Financial Advisory  ...                                NaN
2532433  Risk and Financial Advisory  ...                                NaN
2532434                   Consulting  ...                                NaN
2532435                   Consulting  ...                                NaN
2532436                   Consulting  ...                                NaN

        Header Item Clicked (v56) (evar56)  \
60                                     NaN
61                                     NaN
62                                     NaN
63                                     NaN
64                                     NaN
...                                    ...
2532432                                NaN
2532433                                NaN
2532434                                NaN
2532435                                NaN
2532436                                NaN

        Search Result Clicked Detail (v60) (evar60)  \
60                                              NaN
61                                              NaN
62                                              NaN
63                                              NaN
64                                              NaN
...                                             ...
2532432                                Result title
2532433                                Result title
2532434                                         NaN
2532435                                         NaN
2532436                                         NaN

        Search Result Clicked Subtype (v59) (evar59)  \
60                                               NaN
61                                               NaN
62                                               NaN
63                                               NaN
64                                               NaN
...                                              ...
2532432                                        Pages
2532433                                        Pages
2532434                                          NaN
2532435                                          NaN
2532436                                          NaN

        Search Result Clicked Title (v23) (evar23)  \
60                                             NaN
61                                             NaN
62                                             NaN
63                                             NaN
64                                             NaN
...                                            ...
2532432                      TOD: Talent On Demand
2532433                      TOD: Talent On Demand
2532434                                        NaN
2532435                                        NaN
2532436                                        NaN

        Search Result Clicked Type (v58) (evar58) Search Type (v25) (evar25)  \
60                                            NaN                        NaN
61                                            NaN                        NaN
62                                            NaN                        NaN
63                                            NaN                        NaN
64                                            NaN                        NaN
...                                           ...                        ...
2532432                       Instant Find Result               Instant Find
2532433                       Instant Find Result               Instant Find
2532434                                       NaN                        NaN
2532435                                       NaN                        NaN
2532436                                       NaN   Instant Find DIGS Search

        Search Terms (v26) (evar26)        Capability  \
60                              NaN  Data Field Blank
61                              NaN  Data Field Blank
62                              NaN  Data Field Blank
63                              NaN  Data Field Blank
64                              NaN  Data Field Blank
...                             ...               ...
2532432            talent on demand  Data Field Blank
2532433                         TOD  Data Field Blank
2532434                         NaN  Data Field Blank
2532435                         NaN  Data Field Blank
2532436                         4pl  Data Field Blank

                                   Breadcrumb (v9) (evar9)
60                                                     NaN
61       DeloitteNet > People & Practices > Practice Co...
62       DeloitteNet > People & Practices > Practice Co...
63       DeloitteNet > People & Practices > Practice Co...
64                                                    Home
...                                                    ...
2532432                                                NaN
2532433                                                NaN
2532434                                               Home
2532435                    South Africa > UnityRedirection
2532436                                                NaN

[2503938 rows x 22 columns]

Data Size after dropping duplicated data (based on abstract attribute): (13252, 22)

In [13]:
def dealing_with_null_values(dataset):
    dataset = dataset
    for i in dataset.columns:
        replace = []
        data  = dataset[i].isnull()
        count = 0
        for j,k in zip(data,dataset[i]):
            if (j==True):
                count = count+1
                replace.append('No Information Available')
            else:
                replace.append(k)
        print("Num of null values (",i,"):",count)
        dataset[i] = replace
    return dataset

meta_data = dealing_with_null_values(meta_data)

Num of null values ( ï»¿"User ID (v14) (evar14)" ): 0
Num of null values ( Tenure (yrs) ): 0
Num of null values ( Subregion ): 0
Num of null values ( Service Line ): 0
Num of null values ( Service Area ): 0
Num of null values ( Office ): 0
Num of null values ( Member Firm ): 0
Num of null values ( Level Local ): 0
Num of null values ( Level ): 0
Num of null values ( Function Local ): 0
Num of null values ( Function ): 0
Num of null values ( Country ): 0
Num of null values ( Header Area Clicked (v55) (evar55) ): 8087
Num of null values ( Header Item Clicked (v56) (evar56) ): 8087
Num of null values ( Search Result Clicked Detail (v60) (evar60) ): 12208
Num of null values ( Search Result Clicked Subtype (v59) (evar59) ): 12208
Num of null values ( Search Result Clicked Title (v23) (evar23) ): 12189
Num of null values ( Search Result Clicked Type (v58) (evar58) ): 12189
Num of null values ( Search Type (v25) (evar25) ): 11178
Num of null values ( Search Terms (v26) (evar26) ): 11178
Num of null values ( Capability ): 0
Num of null values ( Breadcrumb (v9) (evar9) ): 7225

In [14]:
meta_data.shape

(13252, 22)

In [15]:
from sklearn.decomposition import PCA
def pca_fun(n_components, data):
    pca = PCA(n_components=n_components).fit(data)
    data = pca.transform(data)
    return data

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

def tfidf(data):
    tfidf = TfidfVectorizer( stop_words='english',use_idf=True)
    tfidf_matrix = tfidf.fit_transform(data)
    return tfidf_matrix

In [18]:
tfidf_matrix = tfidf(meta_data['Header Area Clicked (v55) (evar55)'])

In [19]:
from sklearn.metrics.pairwise import linear_kernel
cosine_similarities = linear_kernel(tfidf_matrix[0:1], tfidf_matrix).flatten()

# 10 most related documents indices
related_docs_indices = cosine_similarities.argsort()[:-11:-1]
print("Related Document:",related_docs_indices)

# Cosine Similarties of related documents
print("Cosine Similarites of related documents",cosine_similarities[related_docs_indices])

Related Document: [6625 7934 8018 8016 8003 7996 7993 7982 7980 7974]
Cosine Similarites of related documents [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

In [20]:
meta_data.iloc[0]['Header Area Clicked (v55) (evar55)']

'Top Nav Menu'

In [21]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt
wordcloud = WordCloud().generate(meta_data.iloc[0]['abstract'])
plt.imshow(wordcloud, interpolation="bilinear")

ModuleNotFoundError: No module named 'wordcloud'

In [22]:
from gensim.models import Doc2Vec

def doc2vec():
    document_tagged = []
    tagged_count = 0
    for _ in meta_data['abstract'].values:
        document_tagged.append(gensim.models.doc2vec.TaggedDocument(_,[tagged_count]))
        tagged_count +=1 
    d2v = Doc2Vec(document_tagged)
    d2v.train(document_tagged,epochs=d2v.epochs,total_examples=d2v.corpus_count)
    return d2v.docvecs.vectors_docs

ModuleNotFoundError: No module named 'gensim'

In [32]:
from sklearn.cluster import KMeans

def kmeans(n_clusters):
    kmean_model = KMeans(n_clusters = n_clusters,random_state=0)
    return kmean_model

data = pd.read_csv('hamburger_menu.csv',encoding='ISO-8859-1')

In [40]:
vet=data.values.astype('U')

In [41]:
kmeans5 = KMeans(5)

%time km5 = kmeans5.fit_predict(vet)

ValueError: could not convert string to float: '2-Sep-20'

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3).fit(X)
data = pca.transform(X)
centroids =  pca.transform(kmeans6.cluster_centers_)